# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deploy admin server

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -o admin_server .

    - name: Debug key
      run: |
        echo "${{ secrets.SSH_KEY }}" | wc -l
        echo "${{ secrets.SSH_KEY }}" | head -1
        echo "${{ secrets.SSH_KEY }}" | tail -1

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Copy binary to VPS
      run: |
           scp -i ~/.ssh/deploy_key admin_server ${{ secrets.USER }}@${{ secrets.HOST }}:/home/pkol/services/admin_server/
  
    - name: Restart via pm2
      run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.USER }}@${{ secrets.HOST }} "pm2 restart go-server"
